### PR TITLE
Not working due to latch conditions

### PR DESCRIPTION
**Pull request by hedrickbt**
This was not working with my 74HC595 as the latching needed to be LOW instead of HIGH.

### CODE REVIEW

**Comment by Simsso** [comment]
I have looked into the suggested changes is detail now and there are a few things not clear to me. Could you please clarify:

- You set the latch pin to `LOW` before shifting out new data (https://github.com/Simsso/ShiftRegister-74HC595-Arduino/pull/6/commits/032c9b85ed5734805a80aa397359440902a0401a#diff-9517b5fd53eb127cde55dd0bd709ca34R36). There is (to the best of my knowledge) no reason to do so.
- No matter whether your shift register is sensitive to changes from `LOW` to `HIGH` or vice-versa, both signal edges are being output by the original version as well. https://github.com/Simsso/ShiftRegister-74HC595-Arduino/blob/master/ShiftRegister74HC595.cpp#L42

**Comment by Simsso** [comment]
Sorry, there is an issue with the version control. If you still think the changes should be merged, please create a new pull request; I didn't mean to close the pull request but cannot re-open. Thank you.

**Comment by hedrickbt** [comment]
@Simsso,

Are you still considering my pull request?  I would rather not have to create another one if you are thinking it isn't valid.

When I tried the original code it wasn't working.  I went to the following places to try to figure out why:
1. https://www.arduino.cc/en/Tutorial/ShftOut12
2. http://weworkweplay.com/play/practical-guide-to-shift-registers/

Once I tried the changes included in the pull request, it resolved the issue.

According to both places, you want to have the latch low before sending the bits and then high when you are done. 

Is the library working for you, as is, on actual hardware?  If so, could you pass along the chip vendor, part number, and Arduino/clone model that is working for you?

I am using https://www.digikey.com/products/en?keywords=296-1600-5-ND

**Comment by Simsso** [comment]
I am definitely considering merging, but first I want to understand why the issue is occurring and whether it makes sense to merge.

From hardware perspective I know that the latch flip flops inside of a shift register react to signal edges. It does not make sense to have a signal edge prior to a shift out. The reason it works anyways is because the registers are only sensitive to a specific signal edge direction, i.e. from `HIGH` to `LOW`. Therefore, it is irrelevant whether the switch from `LOW` to `HIGH` happens prior to shifting out of after. It could happen anytime.

The only thing that is confusing is why you have encountered errors. And yes, the library is being used by many folks, including me, and it seems to work. (One guy has actually used it in combination with more than 10 registers in serial...)

The SRs that I am using are these: https://shiftregister.simsso.de/data-sheet.pdf

Could you try swapping these two lines of code https://github.com/Simsso/ShiftRegister74HC595/blob/master/src/ShiftRegister74HC595.cpp#L52-L53, setting the latch pin to `HIGH` initially (https://github.com/Simsso/ShiftRegister74HC595/blob/master/src/ShiftRegister74HC595.cpp#L30) and see what happens, please?

**Pull request closed without merging**
